apiVersion: v1
kind: Service
metadata:
  name:  payal-rtp-service
  namespace: payal
spec:
  type: NodePort
  selector:
    app: payal-rtp
  ports:
  - nodePort: 30082
    port: 8000
    targetPort: 8000

